# This is a basic workflow to help you get started with Actions

name: Expand AS-SETs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 6,12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bgpq3 whois
          version: 1.0


      # Runs a single command using the runners shell
      #- name: Install bgpq3 and whois
      #  run: sudo apt install -y bgpq3 whois

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          a="\"asn\" = '"
          c="'"
          b=$(whois -h whois.radb.net \!iAS-IU13WAN,5 | tr -d '\n' | grep -Po "AS[0-9]+" | grep -Po "[0-9]+" | awk -v d="' OR \"asn\" = '" '{s=(NR==1?s:s d)$0}END{print s}')
          echo "AS-IU13WAN,$a$b$c" > as-sets.csv
          exclude=$(whois -h whois.radb.net \!iAS-IU13WAN,5 | tr -d '\n' | grep -Po "AS[0-9]+" | grep -Po "[0-9]+" | awk -v d="|" '{s=(NR==1?s:s d)$0}END{print s}')
          readarray -t objects < AS-SET.txt
          for object in "${objects[@]}"
          do
            b=$(whois -h whois.radb.net \!i$object,5 | tr -d '\n' | grep -Po "AS[0-9]+" | grep -Po "[0-9]+" | egrep -v "$exclude" |awk -v d="' OR \"asn\" = '" '{s=(NR==1?s:s d)$0}END{print s}')
            echo "$object,$a$b$c" >> as-sets.csv
          done
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated as-sets.csv
